<?php declare(strict_types=1);
	/**
	 * Copyright (C) Apis Networks, Inc - All Rights Reserved.
	 *
	 * Unauthorized copying of this file, via any medium, is
	 * strictly prohibited without consent. Any dissemination of
	 * material herein is prohibited.
	 *
	 * For licensing inquiries email <licensing@apisnetworks.com>
	 *
	 * Written by Matt Saladna <matt@apisnetworks.com>, March 2019
	 */

	namespace Opcenter\Dns\Providers\Linode;

	class Record extends \Opcenter\Dns\Record
	{

		/**
		 * Override broken CAA formatting in Linode
		 */
		protected function formatCaa() {
			if (0 !== ($pos = strspn($this['parameter'], '0123456789'))) {
				$this['parameter'] = ltrim(substr($this['parameter'], $pos));
			}
		}

		public function setMeta($key, $value = null): \Opcenter\Dns\Record
		{
			if ($this->rr === 'CAA' && $key === 'flags') {
				$value = 0;
			}
			return parent::setMeta($key, $value); // TODO: Change the autogenerated stub
		}

		public function getMeta(string $key)
		{
			if ($this->rr === 'CAA' && $key === 'flags') {
				return 0;
			}

			return parent::getMeta($key);
		}
	}